    <html>
    <head>
<style>
.failure {
background-color: orangered;
}
.success {
background-color: springgreen;
}
</style>
    </head>
    <body>
	<h1>Testing logs for Python</h1>
	<p>Running at Wed 30 Dec 2020 04:07:56 AM EST</p>
  <div id="summary0" class="failure">
    <h2><a href="python_logs.html#pythonlog0">Assignment 0</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog0-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary1" class="failure">
    <h2><a href="python_logs.html#pythonlog1">Assignment 1</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog1-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary2" class="failure">
    <h2><a href="python_logs.html#pythonlog2">Assignment 2</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog2-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary3" class="failure">
    <h2><a href="python_logs.html#pythonlog3">Assignment 3</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog3-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary4" class="failure">
    <h2><a href="python_logs.html#pythonlog4">Assignment 4</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog4-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary5" class="failure">
    <h2><a href="python_logs.html#pythonlog5">Assignment 5</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog5-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary6" class="failure">
    <h2><a href="python_logs.html#pythonlog6">Assignment 6</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog6-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary7" class="failure">
    <h2><a href="python_logs.html#pythonlog7">Assignment 7</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog7-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary8" class="failure">
    <h2><a href="python_logs.html#pythonlog8">Assignment 8</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog8-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary9" class="failure">
    <h2><a href="python_logs.html#pythonlog9">Assignment 9</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog9-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary10" class="failure">
    <h2><a href="python_logs.html#pythonlog10">Assignment 10</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog10-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary11" class="failure">
    <h2><a href="python_logs.html#pythonlog11">Assignment 11</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog11-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary12" class="failure">
    <h2><a href="python_logs.html#pythonlog12">Assignment 12</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog12-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary13" class="failure">
    <h2><a href="python_logs.html#pythonlog13">Assignment 13</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog13-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary14" class="failure">
    <h2><a href="python_logs.html#pythonlog14">Assignment 14</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog14-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary15" class="failure">
    <h2><a href="python_logs.html#pythonlog15">Assignment 15</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog15-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary16" class="failure">
    <h2><a href="python_logs.html#pythonlog16">Assignment 16</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog16-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary17" class="failure">
    <h2><a href="python_logs.html#pythonlog17">Assignment 17</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog17-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary18" class="failure">
    <h2><a href="python_logs.html#pythonlog18">Assignment 18</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog18-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary19" class="failure">
    <h2><a href="python_logs.html#pythonlog19">Assignment 19</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog19-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary20" class="failure">
    <h2><a href="python_logs.html#pythonlog20">Assignment 20</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog20-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary21" class="failure">
    <h2><a href="python_logs.html#pythonlog21">Assignment 21</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog21-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary22" class="failure">
    <h2><a href="python_logs.html#pythonlog22">Assignment 22</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog22-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary23" class="failure">
    <h2><a href="python_logs.html#pythonlog23">Assignment 23</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog23-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary24" class="failure">
    <h2><a href="python_logs.html#pythonlog24">Assignment 24</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog24-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary25" class="failure">
    <h2><a href="python_logs.html#pythonlog25">Assignment 25</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog25-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary26" class="failure">
    <h2><a href="python_logs.html#pythonlog26">Assignment 26</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog26-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary27" class="failure">
    <h2><a href="python_logs.html#pythonlog27">Assignment 27</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog27-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary28" class="failure">
    <h2><a href="python_logs.html#pythonlog28">Assignment 28</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog28-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary29" class="failure">
    <h2><a href="python_logs.html#pythonlog29">Assignment 29</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog29-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary30" class="failure">
    <h2><a href="python_logs.html#pythonlog30">Assignment 30</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog30-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary31" class="failure">
    <h2><a href="python_logs.html#pythonlog31">Assignment 31</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog31-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary32" class="failure">
    <h2><a href="python_logs.html#pythonlog32">Assignment 32</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog32-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary33" class="failure">
    <h2><a href="python_logs.html#pythonlog33">Assignment 33</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog33-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary34" class="failure">
    <h2><a href="python_logs.html#pythonlog34">Assignment 34</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog34-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary35" class="failure">
    <h2><a href="python_logs.html#pythonlog35">Assignment 35</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog35-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary36" class="failure">
    <h2><a href="python_logs.html#pythonlog36">Assignment 36</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog36-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary37" class="failure">
    <h2><a href="python_logs.html#pythonlog37">Assignment 37</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog37-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary38" class="failure">
    <h2><a href="python_logs.html#pythonlog38">Assignment 38</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog38-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary39" class="failure">
    <h2><a href="python_logs.html#pythonlog39">Assignment 39</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog39-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary40" class="failure">
    <h2><a href="python_logs.html#pythonlog40">Assignment 40</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog40-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary41" class="failure">
    <h2><a href="python_logs.html#pythonlog41">Assignment 41</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog41-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary42" class="failure">
    <h2><a href="python_logs.html#pythonlog42">Assignment 42</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog42-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary43" class="failure">
    <h2><a href="python_logs.html#pythonlog43">Assignment 43</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog43-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary44" class="failure">
    <h2><a href="python_logs.html#pythonlog44">Assignment 44</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog44-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary45" class="failure">
    <h2><a href="python_logs.html#pythonlog45">Assignment 45</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog45-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary46" class="failure">
    <h2><a href="python_logs.html#pythonlog46">Assignment 46</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog46-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary47" class="failure">
    <h2><a href="python_logs.html#pythonlog47">Assignment 47</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog47-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary48" class="failure">
    <h2><a href="python_logs.html#pythonlog48">Assignment 48</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog48-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary49" class="failure">
    <h2><a href="python_logs.html#pythonlog49">Assignment 49</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog49-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary50" class="failure">
    <h2><a href="python_logs.html#pythonlog50">Assignment 50</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog50-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary51" class="failure">
    <h2><a href="python_logs.html#pythonlog51">Assignment 51</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog51-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary52" class="failure">
    <h2><a href="python_logs.html#pythonlog52">Assignment 52</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog52-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary53" class="failure">
    <h2><a href="python_logs.html#pythonlog53">Assignment 53</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog53-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary54" class="failure">
    <h2><a href="python_logs.html#pythonlog54">Assignment 54</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog54-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary55" class="failure">
    <h2><a href="python_logs.html#pythonlog55">Assignment 55</a> </h2>
    <p>
      <ul>
        <li> Run : <a href="python_logs.html#pythonlog55-runanswer">error</a></li>
      </ul>
    </p>
  </div>
    <div id="pythonlog0" class="logdetails">
      <h2>Assignment 0 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog0-runanswer">Run for Assignment 0</span></h3>
<pre><code>Guessing setup.py is the python file where main is

Traceback (most recent call last):
  File &quot;setup.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/0-Setup/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog1" class="logdetails">
      <h2>Assignment 1 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog1-runanswer">Run for Assignment 1</span></h3>
<pre><code>Guessing ListIMDB.py is the python file where main is

Traceback (most recent call last):
  File &quot;ListIMDB.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/1-ListIMDB/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog2" class="logdetails">
      <h2>Assignment 2 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog2-runanswer">Run for Assignment 2</span></h3>
<pre><code>Guessing ListEQ.py is the python file where main is

Traceback (most recent call last):
  File &quot;ListEQ.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/2-ListEQ/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog3" class="logdetails">
      <h2>Assignment 3 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog3-runanswer">Run for Assignment 3</span></h3>
<pre><code>Guessing GraphBaconNumber.py is the python file where main is

Traceback (most recent call last):
  File &quot;GraphBaconNumber.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/3-GraphBaconNumber/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog4" class="logdetails">
      <h2>Assignment 4 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog4-runanswer">Run for Assignment 4</span></h3>
<pre><code>Guessing GraphEQ.py is the python file where main is

Traceback (most recent call last):
  File &quot;GraphEQ.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/4-GraphEQ/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog5" class="logdetails">
      <h2>Assignment 5 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog5-runanswer">Run for Assignment 5</span></h3>
<pre><code>Guessing BST.py is the python file where main is

Traceback (most recent call last):
  File &quot;BST.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/5-BstEq/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog6" class="logdetails">
      <h2>Assignment 6 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog6-runanswer">Run for Assignment 6</span></h3>
<pre><code>Guessing GridSquareFill.py is the python file where main is

Traceback (most recent call last):
  File &quot;GridSquareFill.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/6-GridSquareFill/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog7" class="logdetails">
      <h2>Assignment 7 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog7-runanswer">Run for Assignment 7</span></h3>
<pre><code>Guessing GridLyrics.py is the python file where main is

Traceback (most recent call last):
  File &quot;GridLyrics.py&quot;, line 1, in &lt;module&gt;
    from bridges.bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/7-GridLyrics/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog8" class="logdetails">
      <h2>Assignment 8 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog8-runanswer">Run for Assignment 8</span></h3>
<pre><code>Guessing PQBook.py is the python file where main is

Traceback (most recent call last):
  File &quot;PQBook.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/8-PQBook/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog9" class="logdetails">
      <h2>Assignment 9 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog9-runanswer">Run for Assignment 9</span></h3>
<pre><code>Guessing ShortestPathOSM.py is the python file where main is

Traceback (most recent call last):
  File &quot;ShortestPathOSM.py&quot;, line 1, in &lt;module&gt;
    from bridges.color import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/9-ShortestPathOSM/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog10" class="logdetails">
      <h2>Assignment 10 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog10-runanswer">Run for Assignment 10</span></h3>
<pre><code>Guessing HurricaneTracker.py is the python file where main is

Traceback (most recent call last):
  File &quot;HurricaneTracker.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/10-HurricaneTracker/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog11" class="logdetails">
      <h2>Assignment 11 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog11-runanswer">Run for Assignment 11</span></h3>
<pre><code>Guessing 2048Game.py is the python file where main is

Traceback (most recent call last):
  File &quot;2048Game.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/11-2048Game/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog12" class="logdetails">
      <h2>Assignment 12 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog12-runanswer">Run for Assignment 12</span></h3>
<pre><code>Guessing AStarMaze.py is the python file where main is

Traceback (most recent call last):
  File &quot;AStarMaze.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/12-AStarMaze/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog13" class="logdetails">
      <h2>Assignment 13 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog13-runanswer">Run for Assignment 13</span></h3>
<pre><code>Guessing InfiniteRunner.py is the python file where main is

Traceback (most recent call last):
  File &quot;InfiniteRunner.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/13-InfiniteRunner/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog14" class="logdetails">
      <h2>Assignment 14 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog14-runanswer">Run for Assignment 14</span></h3>
<pre><code>Guessing SpreadingFire.py is the python file where main is

Traceback (most recent call last):
  File &quot;SpreadingFire.py&quot;, line 3, in &lt;module&gt;
    from bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/14-SpreadingFire/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog15" class="logdetails">
      <h2>Assignment 15 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog15-runanswer">Run for Assignment 15</span></h3>
<pre><code>Guessing FallingSand.py is the python file where main is

Traceback (most recent call last):
  File &quot;FallingSand.py&quot;, line 3, in &lt;module&gt;
    from bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/15-FallingSand/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog16" class="logdetails">
      <h2>Assignment 16 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog16-runanswer">Run for Assignment 16</span></h3>
<pre><code>Guessing ImagePuzzle.py is the python file where main is

Traceback (most recent call last):
  File &quot;ImagePuzzle.py&quot;, line 1, in &lt;module&gt;
    from bridges import *;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/16-ImagePuzzle/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog17" class="logdetails">
      <h2>Assignment 17 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog17-runanswer">Run for Assignment 17</span></h3>
<pre><code>Guessing ControlsTutorial.py is the python file where main is

Traceback (most recent call last):
  File &quot;ControlsTutorial.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/17-ControlsTutorial/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog18" class="logdetails">
      <h2>Assignment 18 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog18-runanswer">Run for Assignment 18</span></h3>
<pre><code>Guessing ControlsTutorialTwo.py is the python file where main is

Traceback (most recent call last):
  File &quot;ControlsTutorialTwo.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/18-ControlsTutorialTwo/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog19" class="logdetails">
      <h2>Assignment 19 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog19-runanswer">Run for Assignment 19</span></h3>
<pre><code>Guessing BUGSTOMP.py is the python file where main is

Traceback (most recent call last):
  File &quot;BUGSTOMP.py&quot;, line 3, in &lt;module&gt;
    from bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/19-Bugstomp/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog20" class="logdetails">
      <h2>Assignment 20 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog20-runanswer">Run for Assignment 20</span></h3>
<pre><code>Guessing minesweeper.py is the python file where main is

Traceback (most recent call last):
  File &quot;minesweeper.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/20-Minesweeper/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog21" class="logdetails">
      <h2>Assignment 21 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog21-runanswer">Run for Assignment 21</span></h3>
<pre><code>Guessing RaceCar.py is the python file where main is

Traceback (most recent call last):
  File &quot;RaceCar.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/21-RaceCar/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog22" class="logdetails">
      <h2>Assignment 22 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog22-runanswer">Run for Assignment 22</span></h3>
<pre><code>Guessing Snake.py is the python file where main is

Traceback (most recent call last):
  File &quot;Snake.py&quot;, line 3, in &lt;module&gt;
    from bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/22-Snake/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog23" class="logdetails">
      <h2>Assignment 23 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog23-runanswer">Run for Assignment 23</span></h3>
<pre><code>Guessing MountainPaths.py is the python file where main is

Traceback (most recent call last):
  File &quot;MountainPaths.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/23-MountainPaths/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog24" class="logdetails">
      <h2>Assignment 24 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog24-runanswer">Run for Assignment 24</span></h3>
<pre><code>Guessing ImageCompressionKdTree.py is the python file where main is

Traceback (most recent call last):
  File &quot;ImageCompressionKdTree.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/24-ImageCompressionKdTree/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog25" class="logdetails">
      <h2>Assignment 25 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog25-runanswer">Run for Assignment 25</span></h3>
<pre><code>Guessing Patterns.py is the python file where main is

Traceback (most recent call last):
  File &quot;Patterns.py&quot;, line 1, in &lt;module&gt;
    from bridges import *;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/25-Patterns/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog26" class="logdetails">
      <h2>Assignment 26 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog26-runanswer">Run for Assignment 26</span></h3>
<pre><code>Guessing TowersOfHanoi.py is the python file where main is

Traceback (most recent call last):
  File &quot;TowersOfHanoi.py&quot;, line 2, in &lt;module&gt;
    from bridges.bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/26-TowersOfHanoi/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog27" class="logdetails">
      <h2>Assignment 27 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog27-runanswer">Run for Assignment 27</span></h3>
<pre><code>Guessing GameGridAdvanced.py is the python file where main is

Traceback (most recent call last):
  File &quot;GameGridAdvanced.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/27-GameGridBasic/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog28" class="logdetails">
      <h2>Assignment 28 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog28-runanswer">Run for Assignment 28</span></h3>
<pre><code>Guessing BigOhMatters.py is the python file where main is

Traceback (most recent call last):
  File &quot;BigOhMatters.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/28-BigOhMatters/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog29" class="logdetails">
      <h2>Assignment 29 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog29-runanswer">Run for Assignment 29</span></h3>
<pre><code>Guessing SortingBenchmark.py is the python file where main is

Traceback (most recent call last):
  File &quot;SortingBenchmark.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/29-SortingBenchmark/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog30" class="logdetails">
      <h2>Assignment 30 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog30-runanswer">Run for Assignment 30</span></h3>
<pre><code>Guessing TemporalBaconNumber.py is the python file where main is

Traceback (most recent call last):
  File &quot;TemporalBaconNumber.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/30-TemporalBaconNumber/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog31" class="logdetails">
      <h2>Assignment 31 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog31-runanswer">Run for Assignment 31</span></h3>
<pre><code>Guessing TemporalPageRank.py is the python file where main is

Traceback (most recent call last):
  File &quot;TemporalPageRank.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/31-TemporalPageRank/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog32" class="logdetails">
      <h2>Assignment 32 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog32-runanswer">Run for Assignment 32</span></h3>
<pre><code>Guessing TicTacToe.py is the python file where main is

Traceback (most recent call last):
  File &quot;TicTacToe.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/32-TicTacToe/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog33" class="logdetails">
      <h2>Assignment 33 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog33-runanswer">Run for Assignment 33</span></h3>
<pre><code>can't guess a python file
could not run python_answer for assignment in ../assignmentdb/33-AudioMixing/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog34" class="logdetails">
      <h2>Assignment 34 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog34-runanswer">Run for Assignment 34</span></h3>
<pre><code>Guessing GameTutorial.py is the python file where main is

Traceback (most recent call last):
  File &quot;GameTutorial.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/34-GameTutorials/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog35" class="logdetails">
      <h2>Assignment 35 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog35-runanswer">Run for Assignment 35</span></h3>
<pre><code>assignment 35 has no python_answer directory
</code></pre>
</div>
    
    </div>
    <div id="pythonlog36" class="logdetails">
      <h2>Assignment 36 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog36-runanswer">Run for Assignment 36</span></h3>
<pre><code>assignment 36 has no python_answer directory
</code></pre>
</div>
    
    </div>
    <div id="pythonlog37" class="logdetails">
      <h2>Assignment 37 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog37-runanswer">Run for Assignment 37</span></h3>
<pre><code>can't guess a python file
could not run python_answer for assignment in ../assignmentdb/37-BST_Earthquakes/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog38" class="logdetails">
      <h2>Assignment 38 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog38-runanswer">Run for Assignment 38</span></h3>
<pre><code>assignment 38 has no python_answer directory
</code></pre>
</div>
    
    </div>
    <div id="pythonlog39" class="logdetails">
      <h2>Assignment 39 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog39-runanswer">Run for Assignment 39</span></h3>
<pre><code>assignment 39 has no python_answer directory
</code></pre>
</div>
    
    </div>
    <div id="pythonlog40" class="logdetails">
      <h2>Assignment 40 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog40-runanswer">Run for Assignment 40</span></h3>
<pre><code>assignment 40 has no python_answer directory
</code></pre>
</div>
    
    </div>
    <div id="pythonlog41" class="logdetails">
      <h2>Assignment 41 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog41-runanswer">Run for Assignment 41</span></h3>
<pre><code>Guessing SpaceInvaders.py is the python file where main is

Traceback (most recent call last):
  File &quot;SpaceInvaders.py&quot;, line 2, in &lt;module&gt;
    from bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/41-SpaceInvaders/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog42" class="logdetails">
      <h2>Assignment 42 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog42-runanswer">Run for Assignment 42</span></h3>
<pre><code>can't guess a python file
could not run python_answer for assignment in ../assignmentdb/42-Covid/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog43" class="logdetails">
      <h2>Assignment 43 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog43-runanswer">Run for Assignment 43</span></h3>
<pre><code>Guessing spatialindexing.py is the python file where main is

Traceback (most recent call last):
  File &quot;spatialindexing.py&quot;, line 2, in &lt;module&gt;
    from bridges.color import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/43-SpatialIndexing/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog44" class="logdetails">
      <h2>Assignment 44 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog44-runanswer">Run for Assignment 44</span></h3>
<pre><code>assignment 44 has no python_answer directory
</code></pre>
</div>
    
    </div>
    <div id="pythonlog45" class="logdetails">
      <h2>Assignment 45 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog45-runanswer">Run for Assignment 45</span></h3>
<pre><code>Guessing ExplorerRobot.py is the python file where main is

Traceback (most recent call last):
  File &quot;ExplorerRobot.py&quot;, line 2, in &lt;module&gt;
    from bridges import *
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 967, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 668, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 638, in _load_backward_compatible
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/data_source.py&quot;, line 14, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 983, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 963, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 906, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1280, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1254, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1235, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 441, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 594, in spec_from_file_location
  File &quot;/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.1-py3.7.egg/bridges/data_src_dependent/elevation.py&quot;, line 72
    @xll.setter
    ^
IndentationError: expected an indented block
could not run python_answer for assignment in ../assignmentdb/45-ExplorerRobot/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog46" class="logdetails">
      <h2>Assignment 46 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog46-runanswer">Run for Assignment 46</span></h3>
<pre><code>assignment 46 has no python_answer directory
</code></pre>
</div>
    
    </div>
    <div id="pythonlog47" class="logdetails">
      <h2>Assignment 47 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog47-runanswer">Run for Assignment 47</span></h3>
<pre><code>assignment 47 has no python_answer directory
</code></pre>
</div>
    
    </div>
    <div id="pythonlog48" class="logdetails">
      <h2>Assignment 48 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog48-runanswer">Run for Assignment 48</span></h3>
<pre><code>assignment 48 has no python_answer directory
</code></pre>
</div>
    
    </div>
    <div id="pythonlog49" class="logdetails">
      <h2>Assignment 49 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog49-runanswer">Run for Assignment 49</span></h3>
<pre><code>assignment 49 has no python_answer directory
</code></pre>
</div>
    
    </div>
    <div id="pythonlog50" class="logdetails">
      <h2>Assignment 50 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog50-runanswer">Run for Assignment 50</span></h3>
<pre><code>assignment 50 has no python_answer directory
</code></pre>
</div>
    
    </div>
    <div id="pythonlog51" class="logdetails">
      <h2>Assignment 51 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog51-runanswer">Run for Assignment 51</span></h3>
<pre><code>assignment 51 has no python_answer directory
</code></pre>
</div>
    
    </div>
    <div id="pythonlog52" class="logdetails">
      <h2>Assignment 52 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog52-runanswer">Run for Assignment 52</span></h3>
<pre><code>can't guess a python file
could not run python_answer for assignment in ../assignmentdb/52-AudioWave/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog53" class="logdetails">
      <h2>Assignment 53 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog53-runanswer">Run for Assignment 53</span></h3>
<pre><code>assignment 53 has no python_answer directory
</code></pre>
</div>
    
    </div>
    <div id="pythonlog54" class="logdetails">
      <h2>Assignment 54 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog54-runanswer">Run for Assignment 54</span></h3>
<pre><code>assignment 54 has no python_answer directory
</code></pre>
</div>
    
    </div>
    <div id="pythonlog55" class="logdetails">
      <h2>Assignment 55 full log</h2>
    
<div class="failure">
<h3><span id="pythonlog55-runanswer">Run for Assignment 55</span></h3>
<pre><code>can't guess a python file
could not run python_answer for assignment in ../assignmentdb/55-FreqencyPlayer/python_answer
</code></pre>
</div>
    
    </div>
  </body>
