cd python/web_tutorial_mastercopy; make testing; 
make[1]: Entering directory '/home/bridges-testing/bridges-client-testing/python/web_tutorial_mastercopy'
unifdef -DTESTING=1 -o ../web_tutorial_testing/audio_clip.py audio_clip.py ; [ $? != 2 ]
unifdef -DTESTING=1 -o ../web_tutorial_testing/dllist.py dllist.py ; [ $? != 2 ]
unifdef -DTESTING=1 -o ../web_tutorial_testing/bst.py bst.py ; [ $? != 2 ]
unifdef -DTESTING=1 -o ../web_tutorial_testing/earthquake_snippet.py earthquake_snippet.py ; [ $? != 2 ]
unifdef -DTESTING=1 -o ../web_tutorial_testing/minimal_game.py minimal_game.py ; [ $? != 2 ]
unifdef -DTESTING=1 -o ../web_tutorial_testing/imdb_snippet.py imdb_snippet.py ; [ $? != 2 ]
unifdef -DTESTING=1 -o ../web_tutorial_testing/avl.py avl.py ; [ $? != 2 ]
unifdef -DTESTING=1 -o ../web_tutorial_testing/array2d.py array2d.py ; [ $? != 2 ]
unifdef -DTESTING=1 -o ../web_tutorial_testing/array1d.py array1d.py ; [ $? != 2 ]
unifdef -DTESTING=1 -o ../web_tutorial_testing/tree.py tree.py ; [ $? != 2 ]
unifdef -DTESTING=1 -o ../web_tutorial_testing/input_game.py input_game.py ; [ $? != 2 ]
unifdef -DTESTING=1 -o ../web_tutorial_testing/array3d.py array3d.py ; [ $? != 2 ]
unifdef -DTESTING=1 -o ../web_tutorial_testing/circ_sllist.py circ_sllist.py ; [ $? != 2 ]
unifdef -DTESTING=1 -o ../web_tutorial_testing/song_snippet.py song_snippet.py ; [ $? != 2 ]
unifdef -DTESTING=1 -o ../web_tutorial_testing/guttenberg_snippet.py guttenberg_snippet.py ; [ $? != 2 ]
unifdef -DTESTING=1 -o ../web_tutorial_testing/circ_dllist.py circ_dllist.py ; [ $? != 2 ]
unifdef -DTESTING=1 -o ../web_tutorial_testing/osm_snippet.py osm_snippet.py ; [ $? != 2 ]
unifdef -DTESTING=1 -o ../web_tutorial_testing/graph_alist.py graph_alist.py ; [ $? != 2 ]
unifdef -DTESTING=1 -o ../web_tutorial_testing/mountainpass.py mountainpass.py ; [ $? != 2 ]
unifdef -DTESTING=1 -o ../web_tutorial_testing/bintree.py bintree.py ; [ $? != 2 ]
unifdef -DTESTING=1 -o ../web_tutorial_testing/game_snippet.py game_snippet.py ; [ $? != 2 ]
unifdef -DTESTING=1 -o ../web_tutorial_testing/vis_example.py vis_example.py ; [ $? != 2 ]
unifdef -DTESTING=1 -o ../web_tutorial_testing/shape_collection.py shape_collection.py ; [ $? != 2 ]
unifdef -DTESTING=1 -o ../web_tutorial_testing/shakespeare_snippet.py shakespeare_snippet.py ; [ $? != 2 ]
unifdef -DTESTING=1 -o ../web_tutorial_testing/sllist.py sllist.py ; [ $? != 2 ]
unifdef -DTESTING=1 -o ../web_tutorial_testing/display_game.py display_game.py ; [ $? != 2 ]
unifdef -DTESTING=1 -o ../web_tutorial_testing/kdt.py kdt.py ; [ $? != 2 ]
unifdef -DTESTING=1 -o ../web_tutorial_testing/color_grid.py color_grid.py ; [ $? != 2 ]
unifdef -DTESTING=1 -o ../web_tutorial_testing/mllist.py mllist.py ; [ $? != 2 ]
unifdef -DTESTING=1 -o ../web_tutorial_testing/elevation_snippet.py elevation_snippet.py ; [ $? != 2 ]
make[1]: Leaving directory '/home/bridges-testing/bridges-client-testing/python/web_tutorial_mastercopy'
cd python/web_tutorial_testing; make; make run;
make[1]: Entering directory '/home/bridges-testing/bridges-client-testing/python/web_tutorial_testing'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/bridges-testing/bridges-client-testing/python/web_tutorial_testing'
make[1]: Entering directory '/home/bridges-testing/bridges-client-testing/python/web_tutorial_testing'
ASSIGNMENTID=3000 ; for TEST in array1d.py array2d.py array3d.py audio_clip.py avl.py bintree.py bst.py circ_dllist.py circ_sllist.py color_grid.py dllist.py earthquake_snippet.py elevation_snippet.py game_snippet.py graph_alist.py graph_amatrix.py guttenberg_snippet.py imdb_snippet.py kdt.py mllist.py mountainpass.py osm_snippet.py shakespeare_snippet.py shape_collection.py sllist.py song_snippet.py tree.py vis_example.py; do \
	echo "python3 $TEST $ASSIGNMENTID bridges_testing 1321549621122 live" ; \
	      python3 $TEST $ASSIGNMENTID bridges_testing 1321549621122 live ; \
	ASSIGNMENTID=`expr $ASSIGNMENTID + 1`; \
done
python3 array1d.py 3000 bridges_testing 1321549621122 live

Check Your Visualization at the following link:

http://bridges-cs.herokuapp.com/assignments/3000/bridges_testing


python3 array2d.py 3001 bridges_testing 1321549621122 live

Check Your Visualization at the following link:

http://bridges-cs.herokuapp.com/assignments/3001/bridges_testing


python3 array3d.py 3002 bridges_testing 1321549621122 live

Check Your Visualization at the following link:

http://bridges-cs.herokuapp.com/assignments/3002/bridges_testing


python3 audio_clip.py 3003 bridges_testing 1321549621122 live
Num Channels: 2, Sample Rate: 44100, Sample Bits: 32, Num Samples: 220500

Check Your Visualization at the following link:

http://bridges-cs.herokuapp.com/assignments/3003/bridges_testing


python3 avl.py 3004 bridges_testing 1321549621122 live

Check Your Visualization at the following link:

http://bridges-cs.herokuapp.com/assignments/3004/bridges_testing


python3 bintree.py 3005 bridges_testing 1321549621122 live

Check Your Visualization at the following link:

http://bridges-cs.herokuapp.com/assignments/3005/bridges_testing


python3 bst.py 3006 bridges_testing 1321549621122 live

Check Your Visualization at the following link:

http://bridges-cs.herokuapp.com/assignments/3006/bridges_testing


python3 circ_dllist.py 3007 bridges_testing 1321549621122 live

Check Your Visualization at the following link:

http://bridges-cs.herokuapp.com/assignments/3007/bridges_testing


python3 circ_sllist.py 3008 bridges_testing 1321549621122 live

Check Your Visualization at the following link:

http://bridges-cs.herokuapp.com/assignments/3008/bridges_testing


python3 color_grid.py 3009 bridges_testing 1321549621122 live
RLE ran

Check Your Visualization at the following link:

http://bridges-cs.herokuapp.com/assignments/3009/bridges_testing


python3 dllist.py 3010 bridges_testing 1321549621122 live

Check Your Visualization at the following link:

http://bridges-cs.herokuapp.com/assignments/3010/bridges_testing


python3 earthquake_snippet.py 3011 bridges_testing 1321549621122 live
38.1413
-118.0807
27 km S of Mina, Nevada
M 1.3 - 27 km S of Mina, Nevada
1.3
2020-07-01 03:22:32
python3 elevation_snippet.py 3012 bridges_testing 1321549621122 live
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f699c2f8c18>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='cci-bridges-elevation-t.dyn.uncc.edu', port=80): Max retries exceeded with url: /hash?minLat=-98.02593749997456&minLon=41.03133177632377&maxLat=-96.94531249997696&maxLon=42.508577297430456&resX=0.0166&resY=0.0166 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f699c2f8c18>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "elevation_snippet.py", line 31, in <module>
    main()
  File "elevation_snippet.py", line 17, in main
    ele_obj = data_source.get_elevation_data([-98.02593749997456, 41.03133177632377, -96.94531249997696, 42.508577297430456])
  File "/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.0-py3.7.egg/bridges/data_src_dependent/data_source.py", line 684, in get_elevation_data
  File "/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.0-py3.7.egg/bridges/data_src_dependent/data_source.py", line 636, in elevation_server
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='cci-bridges-elevation-t.dyn.uncc.edu', port=80): Max retries exceeded with url: /hash?minLat=-98.02593749997456&minLon=41.03133177632377&maxLat=-96.94531249997696&maxLon=42.508577297430456&resX=0.0166&resY=0.0166 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f699c2f8c18>: Failed to establish a new connection: [Errno -2] Name or service not known'))
python3 game_snippet.py 3013 bridges_testing 1321549621122 live
Dragon Master: Spell Caster
Wii
2.5
['Action']
python3 graph_alist.py 3014 bridges_testing 1321549621122 live
Visualization Title restricted to50 characters. truncated title...

Check Your Visualization at the following link:

http://bridges-cs.herokuapp.com/assignments/3014/bridges_testing


python3 graph_amatrix.py 3015 bridges_testing 1321549621122 live
Visualization Title restricted to50 characters. truncated title...

Check Your Visualization at the following link:

http://bridges-cs.herokuapp.com/assignments/3015/bridges_testing


python3 guttenberg_snippet.py 3016 bridges_testing 1321549621122 live
python3 imdb_snippet.py 3017 bridges_testing 1321549621122 live
Leonard_Nimoy
Stars_of_Star_Wars:_Interviews_From_the_Cast,_The_(1999)
python3 kdt.py 3018 bridges_testing 1321549621122 live

Check Your Visualization at the following link:

http://bridges-cs.herokuapp.com/assignments/3018/bridges_testing


python3 mllist.py 3019 bridges_testing 1321549621122 live

Check Your Visualization at the following link:

http://bridges-cs.herokuapp.com/assignments/3019/bridges_testing


python3 mountainpass.py 3020 bridges_testing 1321549621122 live
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0b356ede48>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='cci-bridges-elevation-t.dyn.uncc.edu', port=80): Max retries exceeded with url: /hash?minLat=6.0&minLon=46.1&maxLat=9.0&maxLon=47.7&resX=0.0166&resY=0.0166 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0b356ede48>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mountainpass.py", line 94, in <module>
    main()
  File "mountainpass.py", line 86, in main
    img = Image()
  File "mountainpass.py", line 7, in __init__
    self.ele_obj = data_source.get_elevation_data([6.0,46.10, 9.0,47.7]) #Switzerland
  File "/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.0-py3.7.egg/bridges/data_src_dependent/data_source.py", line 684, in get_elevation_data
  File "/home/bridges-testing/.local/lib/python3.7/site-packages/bridges-3.1.0-py3.7.egg/bridges/data_src_dependent/data_source.py", line 636, in elevation_server
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='cci-bridges-elevation-t.dyn.uncc.edu', port=80): Max retries exceeded with url: /hash?minLat=6.0&minLon=46.1&maxLat=9.0&maxLon=47.7&resX=0.0166&resY=0.0166 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0b356ede48>: Failed to establish a new connection: [Errno -2] Name or service not known'))
python3 osm_snippet.py 3021 bridges_testing 1321549621122 live
Number of Vertices [Charlotte]: 10150
Number of Edges [Charlotte]: 16186
Position of first vertex: lat=35.224978 long=-80.865467
Cartesian Coordinate of first vertex: 827.1273231300758, -5144.073405550668
python3 shakespeare_snippet.py 3022 bridges_testing 1321549621122 live
Sonnet 133
poem
Beshrew that heart that makes my heart to groan
 For that deep wound it gives my friend and me;
 Is'
python3 shape_collection.py 3023 bridges_testing 1321549621122 live

Check Your Visualization at the following link:

http://bridges-cs.herokuapp.com/assignments/3023/bridges_testing


python3 sllist.py 3024 bridges_testing 1321549621122 live

Check Your Visualization at the following link:

http://bridges-cs.herokuapp.com/assignments/3024/bridges_testing


python3 song_snippet.py 3025 bridges_testing 1321549621122 live
Harder, Better, Faster, Stronger
Daft Punk
Discovery
2001-02-26


[Intro]
Work it, make it
Do it, makes us
Harder, better
Faster, stronger
More than, hour
Hour, never
Ever, after
Work is, over
Work it, make it
Do it, makes us
Harder, better
Faster, stronger

[Chorus 1]
Work it harder, make it better
Do it faster, makes us stronger
More than ever, hour after hour
Work is never over
Work it harder, make it better
Do it faster, makes us stronger
More than ever, hour after hour
Work is never over
Work it harder, make it better
Do it faster, makes us stronger
More than ever, hour after hour
Work is never over
Work it harder, make it better
Do it faster, makes us stronger
More than ever, hour after hour
Work is never over
Work it harder, make it better
Do it faster, makes us stronger
More than ever, hour after hour
Work is never over
Work it harder, make it better
Do it faster, makes us
More than ever, hour after hour
Work is never over
Work it harder, make it better
Do it faster, makes us stronger
More than ever, hour after hour
Work is never over

[Chorus 2]
Work it harder, make it
Do it faster, makes us
More than ever, hour after hour
Work is never over
Work it harder, make it better
Do it faster, makes us stronger
More than ever, hour after hour
Work is never over
Work it, make it better
Do it faster, makes us stronger
More than ever, hour after hour
Work is never over
Work it harder, make it better
Do it faster, makes us stronger
More than ever, hour after hour
Work is never over
Work it harder, make it better
Do it faster, makes us stronger
More than ever, hour after hour
Work is never over

[Outro]
Work it harder
Do it faster
More than ever, hour
Work is never over
Work it harder, make it better
Do it faster, makes us stronger
More than ever, hour after hour
Work is never over


python3 tree.py 3026 bridges_testing 1321549621122 live

Check Your Visualization at the following link:

http://bridges-cs.herokuapp.com/assignments/3026/bridges_testing


python3 vis_example.py 3027 bridges_testing 1321549621122 live
Visualization Title restricted to50 characters. truncated title...

Check Your Visualization at the following link:

http://bridges-cs.herokuapp.com/assignments/3027/bridges_testing


make[1]: Leaving directory '/home/bridges-testing/bridges-client-testing/python/web_tutorial_testing'
